CREATE TABLE IF NOT EXISTS "foreclosure" (
	"id" text PRIMARY KEY NOT NULL,
	"case_number" text,
	"type" text NOT NULL,
	"court" text NOT NULL,
	"year" integer NOT NULL,
	"zhcode" text NOT NULL,
	"stock" text NOT NULL,
	"bid_date" date NOT NULL,
	"bid_times" integer NOT NULL,
	"country" text NOT NULL,
	"city" text NOT NULL,
	"address" text NOT NULL,
	"full_address" text NOT NULL,
	"ratio" text NOT NULL,
	"ping" integer NOT NULL,
	"square_meter" integer NOT NULL,
	"base_price" numeric NOT NULL,
	"total_base_price" numeric NOT NULL,
	"handover" text NOT NULL,
	"empty" text NOT NULL,
	"is_unregistered_building" boolean DEFAULT false NOT NULL,
	"marking" text NOT NULL,
	"remark" text,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
